default:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /


app.annotation:
    resource: "@AppBundle/Controller"
    type:     annotation


_apidoc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc


