comments-new:
    path:     /new
    defaults: { _controller: AppBundle:Comment:new }
    methods:
      - POST

comments-del:
    path:     /delete/{id}
    defaults: { _controller: AppBundle:Comment:delete, id: null }
    methods:
      - POST

comments-list:
    path:     /list/{id}
    defaults: { _controller: AppBundle:Comment:list, id: null }
    methods:
      - GET