default:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: AppBundle:Default:login }
    methods:  [POST]

test:
    path:     /test
    defaults: { _controller: AppBundle:Default:test }
    methods:  [GET]

